name: make lint
on: [push]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
       - uses: actions/setup-node@v2
      with:
        node-version: '14'
      - name: my-step
        run: make lint
