name: make lint
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          python-version: '3.8'
    - name: Poetry Install
      run: | 
        curl -sSL https://install.python-poetry.org | python3
    - name: Install Pip
      run: |
         python -m pip install --upgrade pip 
         pip install -r requirements.txt
    - name: Install Flake8
      run: |
        pip install flake8
    - name: Make Flake8
      run: |
        make lint
