name: make-lint
on:
        push:
                branches: [ master ]
jobs:
        my-job:
                runs-on: ubuntu-latest
                steps:
                          - name: my-step
                            run: make lint
